# Site settings
title: utkarsh2102's GSoC'20
email: utkarsh@debian.org
description: Work done during GSoC 2020.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Utkarsh Gupta
avatar: avatar.png
twitter_username:  utkarsh2102
github_username:   utkarsh2102
site_username:     utkarsh2102
linkedin_username: utkarsh2102

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: ['_pages']
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
