[build]
    publish = "_site"
    command = "bundle exec jekyll build"

[[redirects]]
  from = "https://gsocwithutkarsh2102.netlify.com/*"
  to = "https://gsocwithutkarsh2102.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gsocwithutkarsh2102.netlify.com.com/*"
  to = "https://gsocwithutkarsh2102.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://gsocwithutkarsh2102.netlify.com/*"
  to = "https://gsocwithutkarsh2102.com/:splat"
  status = 301
  force = true
