[build]
    publish = "_site"
    command = "bundle exec jekyll build"

[[redirects]]
  from = "https://utkarsh2102-gsoc2.netlify.com/*"
  to = "https://utkarsh2102-gsoc2.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://utkarsh2102-gsoc2.netlify.com/*"
  to = "https://utkarsh2102-gsoc2.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://utkarsh2102-gsoc2.netlify.com/*"
  to = "https://utkarsh2102-gsoc2.netlify.com/:splat"
  status = 301
  force = true
